spring:
  application:
    name: cs-lab-management-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lab
    password: 
    url: jdbc:mysql://galaxyrockets.top:3306/lab?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 10MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true